version: 1.0.{build}
environment:
  my_secret:
    secure: gDcXlhhrm2A3ZnkjnmhxMLZBovXg0Kgsk23timRCRsc=
  salt_credentialsjson:
    secure: m/VO+Z9myUME+QyPU+lEh41O7C/s1HO297jbF+2VSh1vy43qbqjoardK5vwgg8RXpyXftAcFp5WqC4madpTcPQ==
  salt_googleapisauth:
    secure: q8SCqn3wbGCGTIwI3f1loXG/uWlbg78FaYmUqpg7xlYYMKy9tWmwME8PddfgmQQhK+XU/jX7HHBgZxI8U6yUWw==
  deploy_username:
    secure: ZumRpgIeGcRgW3H7yXK0bQ==
  deploy_password:
    secure: SFAvHfsz398LTl83QbS5gw==
install:
- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
- cmd: appveyor-tools\secure-file -decrypt "Liga\LigaSoft\Utilidades\Backup\Recursos\credentials.json.enc" -secret %my_secret% -salt %salt_credentialsjson%
- cmd: appveyor-tools\secure-file -decrypt "Liga\LigaSoft\Utilidades\Backup\Recursos\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user.enc" -secret %my_secret% -salt %salt_googleapisauth%
- ps: nuget restore Liga\LigaSoft.sln
before_build:
  - cd Liga\LigaSoft\WebPublica
  - npm install
  - npm run build-prod
build:
  project: Liga/LigaSoft.sln
  publish_wap: true
  parallel: true
  verbosity: minimal

for:
  -
    branches:
      only:
        - master
    environment:
      DefaultConnection-Web.config Connection String:
        secure: XCd88qxQ5JDVfoGcLQeYQWrGCU6u6B3IXhiH9F16yEkP5FfTLoWEup0h3mer2aJEKz0030+/xGMv8e9mE4EoPT+Xqo5GNGdYL1S/7lx8bTIHAxf+aPyKE35b1VU7JlIl7sYvWF1FPa27TsSVCe4muQ==
      deploy_server_prod:
        secure: WKFcHMXBFrhnWLgarxvs9pOVG0xeD4uTZXKYgvbNKZp/SOlyrxCYH3Q7SEpjWtvItjQOQ16J+TBtmieZ9J4Y1g==
      deploy_website_prod:
        secure: y5qjD0roTi22GhH9n7jlIw==
    deploy:
      - provider: WebDeploy
        remove_files: true
        skip_dirs: \\App_Data;\\Imagenes;\\logs
        server: $(deploy_server_prod)
        website: $(deploy_website_prod)
        username: $(deploy_username)
        password: $(deploy_password)
        ntlm: false

  -
    branches:
      only:
        - test
    environment:
      DefaultConnection-Web.config Connection String: 
        secure: XCd88qxQ5JDVfoGcLQeYQWrGCU6u6B3IXhiH9F16yEkP5FfTLoWEup0h3mer2aJEMQ3v3eNLGNoG1bGa6EE+gF5ivVxkL4ekjni2H+qCAsOJVQasYy1mhFIqoW7nMtp3FJFhhv8SLhi9Z7xF2updx+Qrmy3d57ZRIi3LQ6p2DmI=
      deploy_server_test:
        secure: qbUfDe0ngl5+/7mkQxs8ByxZ6QB93c59/494w4lEpOai3cgh5bDAiRBRYeOt7hQQ7JkG1kD6wV2IigmoKDvZHD4lsSg4IrSwWOWLSPJCyCI=
      deploy_website_test:
        secure: L4aPGohGkV1xWMMxniWVZryvAIvbB4zCKIDM5WvUh9k=
    deploy:
      - provider: WebDeploy
        remove_files: true
        skip_dirs: \\App_Data;\\Imagenes;\\logs;\\aspnet_client;
        server: $(deploy_server_test)
        website: $(deploy_website_test)
        username: $(deploy_username)
        password: $(deploy_password)
        ntlm: false