version: 1.0.{build}
environment:
  my_secret:
    secure: gDcXlhhrm2A3ZnkjnmhxMLZBovXg0Kgsk23timRCRsc=
  salt_credentialsjson:
    secure: m/VO+Z9myUME+QyPU+lEh41O7C/s1HO297jbF+2VSh1vy43qbqjoardK5vwgg8RXpyXftAcFp5WqC4madpTcPQ==
  salt_googleapisauth:
    secure: q8SCqn3wbGCGTIwI3f1loXG/uWlbg78FaYmUqpg7xlYYMKy9tWmwME8PddfgmQQhK+XU/jX7HHBgZxI8U6yUWw==
  deploy_username:
    secure: TjWwAG8m4aq+7xzrsHJqrw==
  deploy_password:
    secure: SFAvHfsz398LTl83QbS5gw==
install:
- ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
- cmd: appveyor-tools\secure-file -decrypt "Liga\LigaSoft\Utilidades\Backup\credentials.json.enc" -secret %my_secret% -salt %salt_credentialsjson%
- cmd: appveyor-tools\secure-file -decrypt "Liga\LigaSoft\Utilidades\Backup\token.json\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user.enc" -secret %my_secret% -salt %salt_googleapisauth%
- ps: nuget restore Liga\LigaSoft.sln
build:
  project: Liga/LigaSoft.sln
  publish_wap: true
  parallel: true
  verbosity: minimal
after_build:
- ps: Start-Process Liga\LigaSoft\WebPublica\build-prod.bat

for:
  -
    branches:
      only:
        - master
    environment:
      DefaultConnection-Web.config Connection String:
        secure: rseM20eZh0et+yqC++xeyPmLdQj8i/uFhWogVKy4+oC9yw2DvVp3N03FIG0dKzbWDL7PocHCMSZOhXvUx/nqDQpitqW1yyWmWXofWnPFJlNW2d/lgokexRKvhesMXRQkXHJ9iWl5drfr8N+q5sB3Ch+a+GqNKH23kn7nBVA+zoI=
      deploy_server_prod:
        secure: 17WII/5TNwwoQkAp6BZ5Gn9z4iObfqt7VleKl6tCWOqMR1hHkp+eQNgvtAa9PU4nJkf1Tc29ZuFkm9KpQ7l3OA==
      deploy_website_prod:
        secure: y5qjD0roTi22GhH9n7jlIw==
    deploy:
      - provider: WebDeploy
        server: $(deploy_server_prod)
        website: $(deploy_website_prod)
        username: $(deploy_username)
        password: $(deploy_password)
        ntlm: false

  -
    branches:
      only:
        - test
    environment:
      DefaultConnection-Web.config Connection String: 
        secure: rseM20eZh0et+yqC++xeyPmLdQj8i/uFhWogVKy4+oC9yw2DvVp3N03FIG0dKzbWr4GWz5Srkkne6KvdUQhsxpEUuBzNPEaFIwTzhcpLb+sC+qSsWHwW7vfvCVvJdYbaMGJAMT0J8HxIwZMeG/cmwAsiHSYP6V0UFEtGhN0i5lI=
      deploy_server_test:
        secure: 17WII/5TNwwoQkAp6BZ5Gn9z4iObfqt7VleKl6tCWOrZYBuqfL5LyCZL6jHFCts62/0JHvAPxIzFrHdiri2WsA==
      deploy_website_test:
        secure: tRk9SILuLoHrXUKD2DPjYIRy2DXqtX4C2cRmWipUun4=
    deploy:
      - provider: WebDeploy
        server: $(deploy_server_test)
        website: $(deploy_website_test)
        username: $(deploy_username)
        password: $(deploy_password)
        ntlm: false